// Entity schemas for the Academic Journal Tracker.
// Generated by MCD-Flow Phase 1 — do not hand-edit the shapes without updating manifest.json.

import { z } from "zod";

// ---------- Enums ----------

export const FetcherTypeSchema = z.enum([
  "rss",
  "arxiv",
  "crossref",
  "pubmed",
  "html",
]);
export type FetcherType = z.infer<typeof FetcherTypeSchema>;

export const ChannelTypeSchema = z.enum(["email", "webhook"]);
export type ChannelType = z.infer<typeof ChannelTypeSchema>;

// ---------- Journal ----------

export const JournalSchema = z.object({
  id: z.number().int().positive(),
  name: z.string().min(1),
  fetcher_type: FetcherTypeSchema,
  feed_url: z.string().min(1),
  active: z.boolean(),
  created_at: z.string().datetime({ offset: true }),
});
export type Journal = z.infer<typeof JournalSchema>;

// Insert shape (pre-persist; no id, optional created_at).
export const JournalInsertSchema = JournalSchema.omit({
  id: true,
  created_at: true,
}).extend({
  created_at: z.string().datetime({ offset: true }).optional(),
});
export type JournalInsert = z.infer<typeof JournalInsertSchema>;

// ---------- Article ----------

export const ArticleSchema = z.object({
  id: z.number().int().positive(),
  journal_id: z.number().int().positive(),
  title: z.string().min(1),
  url: z.string().url(),
  doi: z.string().nullable(),
  published_at: z.string().datetime({ offset: true }),
  dedupe_key: z.string().min(1),
  created_at: z.string().datetime({ offset: true }),
});
export type Article = z.infer<typeof ArticleSchema>;

// Pre-persistence / post-normalization shape (no id, no dedupe_key yet).
export const NormalizedArticleSchema = z.object({
  title: z.string().min(1),
  url: z.string().url(),
  doi: z.string().nullable(),
  published_at: z.string().datetime({ offset: true }),
});
export type NormalizedArticle = z.infer<typeof NormalizedArticleSchema>;

export const ArticleInsertSchema = ArticleSchema.omit({
  id: true,
  created_at: true,
});
export type ArticleInsert = z.infer<typeof ArticleInsertSchema>;

// ---------- Subscriber ----------

const EmailDestination = z.string().email();
const WebhookDestination = z.string().regex(/^https?:\/\/.+/i);

export const SubscriberSchema = z
  .object({
    id: z.number().int().positive(),
    channel_type: ChannelTypeSchema,
    destination: z.string().min(1),
    active: z.boolean(),
    created_at: z.string().datetime({ offset: true }),
  })
  .refine(
    (s) =>
      s.channel_type === "email"
        ? EmailDestination.safeParse(s.destination).success
        : WebhookDestination.safeParse(s.destination).success,
    { message: "destination does not match channel_type" }
  );
export type Subscriber = z.infer<typeof SubscriberSchema>;

export const SubscriberInsertSchema = z
  .object({
    channel_type: ChannelTypeSchema,
    destination: z.string().min(1),
    active: z.boolean(),
    created_at: z.string().datetime({ offset: true }).optional(),
  })
  .refine(
    (s) =>
      s.channel_type === "email"
        ? EmailDestination.safeParse(s.destination).success
        : WebhookDestination.safeParse(s.destination).success,
    { message: "destination does not match channel_type" }
  );
export type SubscriberInsert = z.infer<typeof SubscriberInsertSchema>;
