// Event / in-memory schemas for the Academic Journal Tracker.
// Generated by MCD-Flow Phase 1.

import { z } from "zod";
import { ChannelTypeSchema, NormalizedArticleSchema } from "./entities";

// ---------- FetchError ----------

export const FetchErrorKindSchema = z.enum([
  "http",
  "timeout",
  "rate_limited",
  "parse",
  "unknown_fetcher_type",
  "unknown",
]);
export type FetchErrorKind = z.infer<typeof FetchErrorKindSchema>;

export const FetchErrorSchema = z.object({
  kind: FetchErrorKindSchema,
  message: z.string(),
  status: z.number().int().optional(),
});
export type FetchError = z.infer<typeof FetchErrorSchema>;

// ---------- FetchResult ----------

export const FetchResultSchema = z.object({
  journal_id: z.number().int().positive(),
  articles: z.array(NormalizedArticleSchema),
  fetched_at: z.string().datetime({ offset: true }),
  error: FetchErrorSchema.nullable(),
});
export type FetchResult = z.infer<typeof FetchResultSchema>;

// ---------- NotificationEvent ----------

export const NotificationStatusSchema = z.enum(["ok", "error"]);
export type NotificationStatus = z.infer<typeof NotificationStatusSchema>;

export const NotificationEventSchema = z.object({
  article_id: z.number().int().positive(),
  subscriber_id: z.number().int().positive(),
  channel: ChannelTypeSchema,
  status: NotificationStatusSchema,
  error_message: z.string().nullable(),
  timestamp: z.string().datetime({ offset: true }),
});
export type NotificationEvent = z.infer<typeof NotificationEventSchema>;

// ---------- CycleSummary ----------

export const CycleSummarySchema = z.object({
  started_at: z.string().datetime({ offset: true }),
  finished_at: z.string().datetime({ offset: true }),
  journals_processed: z.number().int().nonnegative(),
  articles_new: z.number().int().nonnegative(),
  errors: z.number().int().nonnegative(),
});
export type CycleSummary = z.infer<typeof CycleSummarySchema>;

// ---------- JournalResult (per-journal log event) ----------

export const JournalResultSchema = z.object({
  journal_id: z.number().int().positive(),
  journal_name: z.string(),
  fetched: z.number().int().nonnegative(),
  new_articles: z.number().int().nonnegative(),
  errors: z.number().int().nonnegative(),
});
export type JournalResult = z.infer<typeof JournalResultSchema>;
